apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ark-pentaho
  name: ark-pentaho
spec:
  containers:
  - env:
    image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_pentaho:latest
    imagePullPolicy: Always
    #command: ["/bin/sleep", "180d"]
    name: ark-pentaho
    ports:
    - containerPort: 2002
  hostname: ark-pentaho
  imagePullSecrets:
  - name: aws-arkcase-pull
